### PR TITLE
Patrick/info updates

### PR DESCRIPTION
**Pull request by shihpatrick**
made small info updates on the main page

**caution**: i couldn't log in locally and couldn't figure it out why, but i changed the application to just a text block. i'm guessing there won't be a stylistic issue but check it out if you can.

### CODE REVIEW

**Comment by shihpatrick** [comment]
travis says i didnt pass a test, suggested it's because i didn't run prettier with these files
``` 
Forgot to run prettier? There are files without correct code style:
ideahacks/db/index.js
ideahacks/db/scripts/LoadParts.js
```
but i didn't touch any of these files?

**Comment by jeffreyxchan** [comment]
Info changes on the main page look good :)

Don't know why you can't login locally, but you might want to make sure that you're on WIFI (and not WEB), check that there are no database connection errors in your console when running the server, make sure the email you're using is `patrickshih@g.ucla.edu`, and you can reset your password if want to.

Instead of commenting out the entire application, could you instead comment out the "Application" option on the navbar (found in /views/partials/navbar.hbs) and also go into /ideahacks/routes/dashboard/index.js and comment out the two routes for application. Just a cleaner change and will disable all application features entirely.

Also, just run `npm run format` before pushing and that should take care of the travis problem. Make sure you have all the packages downloaded with `npm install`

**Comment by shihpatrick** [comment]
Looked for everything, and still can't log-in? Getting this error when trying to reset password: 
```
(node:2004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unauthorized (401)
  The provided authorization grant is invalid, expired, or revoked
    null
    null
```

lol i've tried to make a new account with `@ucla.edu` (rather than `@g.ucla.edu`). i'm wondering if it's worth putting this check in w next year's registration? 

*UPDATE: still can't log-in, please try locally to see if everything is proper :/*

**Comment by shihpatrick** [comment]
lol i made a new account with `@ucla.edu` (rather than `@g.ucla.edu`). i'm wondering if it's worth putting this check in w next year's application?

**Review by jeffreyxchan — APPROVED** [review]

**Pull request merged**
